version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_ADDR=localhost:6379
      - REDIS_PASSWORD=mysecretpassword
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "mysecretpassword"]

volumes:
  redis-data:
